BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Nijō Castle','https://dskyoto.s3.amazonaws.com/gallery/full/1514/5559/8500/04-20140407_NijoCastle-32.jpg', 'Japans most spectacular feudal castle', 'Himeji Castle, also known as Shirasagijo ("White Heron Castle") due to its elegant, white appearance, is widely considered Japans most spectacular castle for its imposing size, beauty, and well-preserved complex grounds. The castle, a national treasure and a UNESCO world heritage site, has survived many years without being destroyed by war, earthquake, or fire, maintaining its original structures.', '541 Nijojocho, Nakagyo Ward, Kyoto, 604-8301, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Himeji Castle','https://www.japan-guide.com/g21/740/3501_11.jpg', 'Ancient white heron', 'Himeji Castle, often called the White Heron Castle, stands as a pinnacle of 17th-century Japanese castle architecture, incorporating 83 buildings within its complex. Designated as Japans first UNESCO World Heritage Site in 1993, its recognized for its magnificent defensive structures and aesthetic beauty. Uniquely, it has never been destroyed by war, earthquake, or fire, maintaining its original form for centuries. The castles roof tiles were fired at 1,150 degrees Celsius, making them exceptionally durable and are marked with the crests of the castles historic lords, including the Ikeda clans swallowtail butterfly and paulownia flower.', '68 Honmachi, Himeji, Hyogo 670-0012, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Osaka Castle','https://resources.matcha-jp.com/resize/720x2000/2023/03/28-136333.webp', 'Icon of unity', 'Osaka Castle is a symbol of Japans unification, constructed in 1583 by Toyotomi Hideyoshi on the ruins of the Ishiyama Honganji Temple. Throughout its history, the castle has experienced destruction and subsequent rebuilding, notably after the Siege of Osaka, when it fell to the Tokugawa clan. The current reconstruction from 1931 stands as a museum and features an observation deck with panoramic views of Osaka. The castle is distinguished by its use of gold leaf decorations and large stones in its construction, showcasing Hideyoshis ambition and the architectural ingenuity of the era. Osaka Castles grounds are a popular spot for cherry blossom viewing, encapsulating the beauty of Japanese nature alongside historic grandeur.', '1-1 Osakajo, Chuo Ward, Osaka, 540-0002, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Matsumoto-jō Castle','https://www.centrair.jp/en/special/campaign/snowtravel-japan/assets/img/matsumoto/common/spot-1.jpg', 'The Crow Castle', 'Matsumoto Castle, also known as the Crow Castle due to its striking black exterior, is one of Japans premier historic castles and a National Treasure. The castles main tower, which dates back to the late sixteenth century, is the oldest surviving such structure in Japan, making it a significant cultural and historical site. Notably, the castle features a gun museum on its second floor and is surrounded by three moats, setting it apart in its defensive capabilities and architectural beauty. Matsumoto Castle is not just a relic of the past; it actively hosts cultural events such as the Taiko Drum Festival and Takigi Noh plays, and is a popular spot for cherry blossom viewing in April.', '4-1 Marunouchi, Matsumoto, Nagano 390-0873, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Nagoya Castle','https://cdn.cheapoguides.com/wp-content/uploads/sites/3/2020/05/nagoya-castle-aichi-iStock-873850248-1024x685.jpg', 'The Golden Shachihoko', 'Nagoya Castle is famed for its magnificent golden shachihoko (tiger-headed carp) statues that adorn the castles rooftops, symbolizing protection from fire. Constructed on the orders of Tokugawa Ieyasu in the early 17th century, the castle was a pivotal location during the Edo period, serving both as a residence for one of the Tokugawa family branches and a military fortress. While much of the original structure was destroyed during World War II, the castle has undergone extensive reconstruction, including the rebuilding of the Honmaru Palace, which showcases Edo period architecture and craftsmanship. Today, Nagoya Castle stands as a prominent cultural landmark, featuring beautifully recreated interiors and exhibits on the castles and citys history.', '1-1 Honmaru, Naka Ward, Nagoya, Aichi 460-0031, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Matsuyama-jō Castle','https://en.japantravel.com/photo/poi-146-208131/1200x630/ehime-matsuyama-castle-208131.jpg', 'Feudal elegance', 'Matsuyama Castle, constructed between 1602 and 1628 and later assigned to the Matsudaira family, stands as a testament to Japans feudal architecture. Rebuilt in 1854 after being struck by lightning in 1820, the castle features a simple interior across its three floors and a basement. Its walls are adorned with black wooden panels, and it has been recognized as an Important Cultural Property since 1935. The castle grounds are celebrated for their cherry blossoms, making it a picturesque site in spring. A museum within the main keep offers insights into the castles history, complemented by an observation deck providing sweeping views of Matsuyama and the Seto Inland Sea.', '1 Marunouchi, Matsuyama, Ehime 790-0008, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Matsue-jō Castle','https://www.japanexplorer.com.au/wp-content/uploads/2017/11/Matsue-Castle-1-e1510717665521.jpg', 'Plover Castle', 'Matsue Castle, known for its nickname "Plover Castle" due to its elegant appearance, is one of the few remaining medieval castles in Japan that still retains its original wooden structure. Constructed between 1607 and 1611 under the order of Horio Yoshiharu, a significant lord of the Edo period, the castle has withstood the test of time, including the Meiji Restoration period when many Japanese castles were dismantled. The castles architecture is noteworthy for its black tiles, creating a striking contrast against the white plaster of its walls, and it is surrounded by a moat, enhancing its defensive features as well as its scenic beauty. Now a popular tourist destination, Matsue Castle offers visitors a glimpse into Japans samurai past, with exhibitions that display armor, weapons, and other historical artifacts. The surrounding area, including the castle grounds, is a favored spot for cherry blossom viewing, adding to the castles charm and attractiveness.', '1-5 Tonomachi, Matsue, Shimane 690-0887, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Inuyama Castle','https://www.nagoyaisnotboring.com/wp-content/uploads/2021/03/Inuyama-Castle.jpg', 'Japans oldest castle tower', 'Inuyama Castle, perched on a hill overlooking the Kiso River, is celebrated as the oldest surviving castle tower in Japan, dating from the 1580s. This National Treasure, known for its small but complex design, offers varied silhouettes from different angles. The castle has seen numerous rebuilds, with significant work by Oda Nobukatsu, Oda Nobunagas son, shaping its current form. It was once a crucial defensive hold against Nobunagas unification ambitions, witnessing many historical turnovers before being governed by the Naruse clan under the Tokugawa shogunate. Remarkably, it remained privately owned until 2004, when it was entrusted to a foundation established by Aichi Prefectures Board of Education.', 'Kitakoken-65-2 Inuyama, Aichi 484-0082, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Hiroshima Castle','https://i0.wp.com/www.wannabeeverywhere.com/wp-content/uploads/2018/03/f41605056.jpg?ssl=1', 'The Carp Castle', 'Hiroshima Castle, also known as Carp Castle, was originally constructed in 1589 by Mori Terumoto, whose clan was later displaced following the Battle of Sekigahara. The castle was a symbol of power in the Chugoku region and served as a military headquarters during the Imperial Japanese Armys presence. The original structure was destroyed by the atomic bomb in 1945, and the current castle is a replica built in 1958, housing a museum dedicated to Hiroshimas history before World War II. The castle is surrounded by a moat and features a main keep with an exhibit on Japanese castles, samurai culture, and the history of Hiroshima, offering a panoramic view of the city from its top floor.', '21-1 Motomachi, Naka Ward, Hiroshima, 730-0011, Japan');
insert into castle (castle_name, castle_banner_photo, short_desc, long_desc, address) 
values('Edo Castle Ruins','https://www.jcastle.info/images/e/e7/Edo100.jpg', 'Heart of historical Tokyo', 'The Edo Castle, initially built by Ōta Dōkan in 1457, later became the formidable base of Tokugawa Ieyasu, who established the Tokugawa shogunate there. This castle, situated in what is now the Tokyo Imperial Palace area, served as the epicenter of Japanese political power for over 260 years. Despite the destruction of many of its structures over time, including being heavily damaged by fires and earthquakes, parts of the castles walls, moats, and some buildings still stand today. The ruins of Edo Castle, particularly the East Gardens of the Imperial Palace, offer visitors a glimpse into the castles historic past and the chance to explore the remnants of what was once the biggest castle in Japan. The site is significant not only for its historical and cultural value but also for its transformation into a symbol of Tokyos resilience and enduring legacy.', '1-1 Chiyoda, Chiyoda City, Tokyo 100-8111, Japan');


COMMIT TRANSACTION;
